[workspace]
resolver = "2"
members = [
    "crates/amethyst",
    "crates/amethyst-binary",
    "crates/amethyst-log",
    "crates/rakethyst"
]

default-members = ["crates/amethyst"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["full"] }
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
log = { version = "0.4.27", features = ["std"] }
chrono = "0.4.40"
bytes = "1.10.1"
amethyst-binary = { version = "0.1.0", path = "crates/amethyst-binary" }
amethyst-log = { version = "0.1.0", path = "crates/amethyst-log" }
rakethyst = { version = "0.1.0", path = "crates/rakethyst" }
rand = "0.9.1"
hex = "0.4.3"
dashmap = "6.1.0"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
